security:
  oauth2:
    client:
      clientId: 583296129844490
      clientSecret: #https://developers.facebook.com/apps/583296129844490/settings/basic/ get it from here when you login
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token       
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
